name: Build CI wheels

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
    - name: Dummy build
      run: echo "compiling..."
  publish:
    if: github.event.release.released
    name: Publish
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Publish dummy
        run: echo "publishing..."
